Cloud bastion
Otus-DevOps-2020-02/holybrother_infra pull request #2
Opened 2020-04-09 17:18 UTC by holybrother

# holybrother_infra
holybrother Infra repository

#####
Самостоятельное задание
#####
Для удобного подключения используем jump до локального хоста, предварительно настроив SSH forwarding
```ssh -J appuser@35.246.113.27 appuser@10.154.0.3```
Для наиболее удобного подключения создадим файл конфига в том же каталоге ~/.ssh с именем config со следующим содержимым:
```Host bastion
        User professional
        PreferredAuthentications publickey
        IdentityFile ~/.ssh/professional
        Hostname 35.246.113.27

```Host bastionlocal
        User professional
        Hostname 10.154.0.3
        ProxyJump bastion
Подключаемся по ssh к bastion/bastionlocal
Данные по подключению:
bastion_IP = 35.246.113.27
someinternalhost_IP = 10.154.0.3

2020-04-09 18:16 UTC, holybrother commented
Подскажите, что не так, запарился уже с этой проблемой... Подключение работает...
Из-за работы не могу успевать за курсом, хочу на этой неделе все сделать и догнать всех, но эта ошибка меня блочит...

2020-04-10 07:11 UTC, mrgreyves requested changes
Здравствуйте!) Вы тестировали подключение с ПК? Есть ли там какие то проблемы? Настроили корректно firewall в GCP?)

2020-04-10 07:54 UTC, holybrother commented
> Здравствуйте!) Вы тестировали подключение с ПК? Есть ли там какие то проблемы? Настроили корректно firewall в GCP?)

Да, с любого ПК подключение работает.
![image](https://user-images.githubusercontent.com/13042778/78973557-60c40480-7b3a-11ea-8014-7100db3883ab.png)
В GCP создано правило и его тэг привязан к bastion (внешнему хосту)
![image](https://user-images.githubusercontent.com/13042778/78973755-ba2c3380-7b3a-11ea-8afc-b1d5e51cc0f9.png)
![image](https://user-images.githubusercontent.com/13042778/78973810-d62fd500-7b3a-11ea-96e5-104e6aa54bc4.png)
Так же настроен ssl.. сразу не получалось из-за каких-то проблем с pritunl..
![image](https://user-images.githubusercontent.com/13042778/78973961-1a22da00-7b3b-11ea-869d-6e9d42e52abd.png)

2020-04-10 08:02 UTC, holybrother commented
![image](https://user-images.githubusercontent.com/13042778/78974461-3f641800-7b3c-11ea-81e1-862bdaacaec7.png)
Вот ещё скриншот

2020-04-11 21:13 UTC, holybrother commented
Что делать то? Почему билд не проходит?

2020-04-13 21:03 UTC, holybrother reviewed
Переделал всё, понял ошибки..

2020-04-14 06:06 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!

2020-04-14 06:06 UTC, mrgreyves commented on README.md
> +Host bastion User professional PreferredAuthentications publickey IdentityFile ~/.ssh/professional Hostname 35.246.113.27 Host bastionlocal User professional Hostname 10.154.0.3 ProxyJump bastion
Конфиг немного поехал =(

2020-04-14 08:20 UTC, merged